local SwordList = {
    "Abyssal Blade",
    "Abyssal Shield",
    "Abyssal Slicer",
    "Abyssal Sovereign",
    "Abysspiercer",
    "Ace",
    "Aether Katana",
    "Aether Shardblade",
    "Aetherial Azure Katana",
    "Aetherial Azure Reckoner",
    "Aetherial Kunai",
    "Aetherial Lance",
    "Aetherion",
    "Aethertech Blade",
    "Aetherwatch Blade",
    "Aetherwatch Scythe",
    "Aetherwing Blade",
    "Alien Spiderblade",
    "Alien's Slicer",
    "Aligned Constellation",
    "All-Star Striker",
    "Allseeing Seer",
    "Allseeing Spear",
    "Alpha Mode",
    "Amber Saber",
    "Amethyst Backblade",
    "Amethyst Blade",
    "Amethyst Bloomblade",
    "Amethyst Dagger",
    "Amethyst Fireblade",
    "Amethyst Greatsword",
    "Amethyst Slicer",
    "Amethyst Sunblade",
    "Amethyst Veil",
    "Amour's Radiance",
    "Ancient Dagger",
    "Ancient Defender",
    "Ancient Iceblade",
    "Ancient Light",
    "Ancient Trident",
    "Angel Greatsword",
    "Angelic Blaster",
    "Angelic Cleaver",
    "Anime Sword",
    "Apex Blade",
    "Apocalypse Edge",
    "Aqualure",
    "Aquatic Bow",
    "Aquatic Greatsword",
    "Arachne Blade",
    "Arachne Scythe",
    "Arachnoblade",
    "Arcane Staff",
    "Architect",
    "Arctic Edge",
    "Arctic King's Blade",
    "Ashen Crescent",
    "Ashen Edge",
    "Ashen Fang",
    "Asteroid Fang",
    "Astraea Blade",
    "Astraea Staff",
    "Astral Axe",
    "Astral Blade",
    "Astral Bow",
    "Astral Edge",
    "Astral Fang",
    "Astral Riftblade",
    "Astral Sword",
    "Astral Thorn",
    "Astral Vanguard",
    "Augmented Saber",
    "Aurelfrost Fang",
    "Aurelius",
    "Aurora Antlers",
    "Aurora Blade",
    "Aurora Bow",
    "Aurora Carver",
    "Aurora Dancer",
    "Aurora Fang",
    "Aurora Protector",
    "Aurora Saber",
    "Aurora Shard",
    "Aurora Slash",
    "Aurora Warden",
    "Aurora Warrior",
    "Aurora's Blade",
    "Aurora's Edge",
    "Aurora's Ice Staff",
    "Aurora's Wrath",
    "Aurorum",
    "Aurum Etherius",
    "Autumn Edge",
    "Autumn Sovereign",
    "Avalanche Blade",
    "Avis Scythe",
    "Axe of Balance",
    "Axe of Love",
    "Axe Of Time",
    "Azure Aegis",
    "Azure Blueblade",
    "Azure Thunderbolt",
    "Azurethorn Blade",
    "Azurethorn Scythe",
    "BAH",
    "Ban Hammer",
    "Banana Sword",
    "Barnaclaw",
    "Barnacle Blade",
    "Base Sword",
    "Baseball Bat",
    "Battle Axe",
    "Beached Sword",
    "Biohazard Sword",
    "Black Cat Blade",
    "Black Cat Scythe",
    "Black Hole Edge",
    "Black Ninja Katana",
    "Black Ninja Star",
    "Black Oni Katana",
    "Blackhole Gauntlets",
    "Blackhole Katana",
    "Blackhole Scythe",
    "Blackhole Set",
    "Blackhole Sword",
    "Blade of Eras",
    "Blade of Sorrows",
    "Blade of the Damned",
    "Blade of the Fallen King",
    "Blaze Blade",
    "Blazebite",
    "Blazing Azure Talon",
    "Blazing Saber",
    "Blazing Temple",
    "Blizzard Blade",
    "Blizzard Cleaver",
    "Blizzard Fang",
    "Blizzard Katana",
    "Blizzard Kingscythe",
    "Blizzard Skater",
    "Blizzard Slayer",
    "Block Buster",
    "Blocky Sword",
    "Bloodfang Halberd",
    "Bloodgazer's Edge",
    "Bloodline Blade",
    "Bloodline Scythe",
    "Bloodmoon Blade",
    "Bloodmoon Scythe",
    "Bloodpetal Blade",
    "Bloodpetal Blaster",
    "Bloodreaver",
    "Bloom Katana",
    "Bloom Shuriken",
    "Blooming Katana",
    "Bloomlight Greatscythe",
    "Bloomveil Kunai",
    "Bloomveil Lance",
    "Blossom Blade",
    "Blossom Dragon",
    "Blossom Katana",
    "Blossom Scythe",
    "Blossoming Edge",
    "Blue Ninja Katana",
    "Blue Ninja Star",
    "Blue Oni Katana",
    "Blue Royal Greatsword",
    "Bobber",
    "Bone",
    "Bonecrusher",
    "Bonsai Tree",
    "Boreal Frostreaver",
    "Borealis",
    "Boundless Reaver",
    "Bowtie Blade",
    "Breakerblade",
    "Breezeflare Sword",
    "Briar Blade",
    "Brick Cleaver",
    "Brine Blade",
    "Broken Honor",
    "Bronze Staff",
    "Bronze Sword",
    "Brutality Affection Bat",
    "Bubble Blade",
    "Bubble Blaster",
    "Bubble Wand",
    "Bunny",
    "Bunny Basher",
    "Bunny Bite",
    "Bunny Staff",
    "Burnt Relic",
    "Butterfly Blade",
    "Butterfly Bow",
    "Butterfly Wingsword",
    "Calamity Guardian",
    "Candy Cane Cutter",
    "Candy Cutter",
    "Candycane",
    "Candycane Blaster",
    "Candycane Crusher",
    "Candycane Katana",
    "Candycane Sniper",
    "Capuchino Assassino Blade",
    "Carrion Carver",
    "Carrot Cleaver",
    "Cat Paw",
    "Cavern Cutter",
    "Celebration Blade",
    "Celebration Edge",
    "Celebration Spark",
    "Celebration Sword",
    "Celestara",
    "Celestial Greatsword",
    "Celestial Lance",
    "Celestial Saber",
    "Celestial Spear",
    "Celestial Staff",
    "Celestial Vanguard",
    "Celestial Whisper",
    "Cerberus",
    "Chained Scorpion",
    "Champion Scythe",
    "Champion's Edge",
    "Chaos Dagger",
    "Chaos Sword",
    "Chimera's Bane",
    "Choco Bunny Blade",
    "Christmas Axe",
    "Christmas Blade",
    "Christmas Scythe",
    "Christmas Staff",
    "Chroma Ban Hammer",
    "Chroma Blade",
    "Chroma Blaster",
    "Chroma Cards",
    "Chroma Chick Blade",
    "Chroma Fortune Cleaver",
    "Chroma Fragment",
    "Chroma Ninja Katana",
    "Chroma Ninja Star",
    "Chroma Oni Katana",
    "Chroma Pearlblade",
    "Chroma Scythe",
    "Chroma Seal",
    "Chroma Shortaxe",
    "Chroma Shuriken",
    "Chroma Sword",
    "Chrono Blade",
    "Chrono Edge",
    "Chrono Fang",
    "Chrono Saber",
    "Chrono Shard",
    "Chrono Slasher",
    "Chrono's Descent",
    "Cinder Fang",
    "Cinder Shard Katana",
    "Clans King",
    "Clans Warrior",
    "Clockwork Blueblade",
    "Clockwork Cutlass",
    "Clockwork Cutter",
    "Cloud",
    "Cloud Rapier",
    "Cloud Sword",
    "COAL",
    "Coconut Crusher",
    "Coffin",
    "Comet Shard",
    "Comically Large Spoon",
    "Confetti Cleaver",
    "Coral Fang",
    "Coral Greatsword",
    "Coral Sword",
    "Corrupt Blossom Blade",
    "Corrupt Blossom Bow",
    "Corrupted Bow",
    "Corrupted Frostblade",
    "Corrupted Halberd",
    "Corrupted Heartbreaker",
    "Corrupted Kunais",
    "Corrupted Loveblade",
    "Corrupted Staff",
    "Corrupted Trident",
    "Cosmic Crusher",
    "Cosmic Edge",
    "Cosmic Keystone",
    "Cosmic Starblade",
    "Cosmic Wraithclaws",
    "Cosmic Wrath",
    "Countdown Edge",
    "Court Dominator",
    "Crane Wing",
    "Crescendo",
    "Crescent Saber",
    "Crimson Backblade",
    "Crimson Blade",
    "Crimson Eclipse",
    "Crimson Fall",
    "Crimson Fang",
    "Crimson Gleam",
    "Crimson Hacker",
    "Crimson Katana",
    "Crimson Regent",
    "Crimson Slicer",
    "Crimson's Cat Racket",
    "Crown Scythe",
    "Crownslayer",
    "Cruz Dagger",
    "Cryo Shard",
    "Cryoscourge",
    "Cryostorm Cleaver",
    "Cryostorm Saber",
    "Crypt Keeper",
    "Crystal Blade",
    "Crystal Breaker",
    "Crystal Carver",
    "Crystal Fairyblade",
    "Crystal Greatblade",
    "Crystal Hammer",
    "Crystal Reaperblade",
    "Crystal Reaver",
    "Crystal Scissors",
    "Crystal Shard",
    "Cupid's Bow",
    "Cupid's Staff",
    "Curse of the Nile",
    "Cursed Abyss",
    "Cursed Blade",
    "Cursed Ink",
    "Cursed Obsession",
    "Cursed Relic Greatblade",
    "Cursed Scythe",
    "Cyber Blade",
    "Cyber Cleaveblade",
    "Cyber Egg Cleaver",
    "Cyber Egg Sword",
    "Cyber King's Sword",
    "Cyber Scythe",
    "Cyber Sickle",
    "Cyber Slasher",
    "Cyber Staff",
    "Cyber Sweeper",
    "Cyber Thorn",
    "Cyborg Blade",
    "Cyborg Sword",
    "Cybotic Champion",
    "Cybotic Greatsword",
    "Cybotic Scythe",
    "Cypress Fang",
    "Dark Blade",
    "Darkheart",
    "Data Dagger",
    "Dawn Shard",
    "Dawnblade",
    "Dawnbringer",
    "Dawnpiercer",
    "Dawnstep Edge",
    "Death Call Blade",
    "Death Call Scythe",
    "Deepcurrent",
    "Deepsea Reaver",
    "Demonblade",
    "Demonic Blade",
    "Demonic Greatsword",
    "Demonic Scythe",
    "Depths Blaster",
    "Desert Blade",
    "Desert Claws",
    "Devil Greatsword",
    "Devil Hornblade",
    "Devil Katana",
    "Diamond Blade",
    "Diamond Slicer",
    "Diamond Spear",
    "Diamond Starblade",
    "Diamond Sword",
    "Digital Edge",
    "Distorted Longsword",
    "Divine Blaster",
    "Divine Scepter of Eternity",
    "Divine Sword",
    "Divinity Blade",
    "Divinity Scythe",
    "DJ's Sword of Agility",
    "Doom's Whisper",
    "Double Sided Prismatic",
    "Draconic Blade",
    "Draconic Bow",
    "Draconic Twinblade",
    "Draconis Emerald",
    "Dragon Blade",
    "Dragon Katana",
    "Dragon Scythe",
    "Dragon Slayer",
    "Dragon Spirit Spear",
    "Dragon Spirit Sword",
    "Dragon Sword",
    "Dragon Tail Fan",
    "Dragon's Claw",
    "Dragon's Lunar Requiem",
    "Dragon's Omen",
    "Dragon's Spines",
    "Dragon's Triumph",
    "Dragon's Wraith",
    "Dragonborne",
    "Dragonfire Katana",
    "Dragonslayer Blade",
    "Dreadbone Greataxe",
    "Dreadborn Blade",
    "Dreadborn Scythe",
    "Dreadclaw",
    "Dreadfang Pike",
    "Dreadspire Blade",
    "Dream Blade",
    "Dream Scythe",
    "Dripfang",
    "Dual Abyssal Blade",
    "Dual Abyssal Set",
    "Dual Aetherial Azure Katana",
    "Dual Aetherial Azure Reckoner",
    "Dual Aetherial Kunai",
    "Dual Aetherwatch Blade",
    "Dual Aetherwatch Scythe",
    "Dual Arachne Blade",
    "Dual Arachne Scythe",
    "Dual Astraea Blade",
    "Dual Astraea Set",
    "Dual Astral Swords",
    "Dual Astral Vanguard",
    "Dual Aurum Etherius",
    "Dual Azurethorn Blade",
    "Dual Azurethorn Scythe",
    "Dual Black Cat Blade",
    "Dual Black Cat Scythe",
    "Dual Blackhole Katana",
    "Dual Blackhole Scythe",
    "Dual Bloodline Blade",
    "Dual Bloodline Scythe",
    "Dual Bloodmoon Blade",
    "Dual Bloodmoon Scythe",
    "Dual Bloodpetal Blade",
    "Dual Bloodpetal Blaster",
    "Dual Bloom Katana",
    "Dual Bloomveil Kunai",
    "Dual Blossom Blade",
    "Dual Blossom Scythe",
    "Dual Blue Bunny Katana",
    "Dual Blue Bunny Scythe",
    "Dual Bubble Blade",
    "Dual Bubble Blasters",
    "Dual Butterfly Blade",
    "Dual Candycane Blasters",
    "Dual Cherry Blossom Blade",
    "Dual Chroma Blasters",
    "Dual Chroma Energy Sword",
    "Dual Chroma Set",
    "Dual Corrupt Blossom Blade",
    "Dual Corrupted Fan",
    "Dual Crimson Eclipse",
    "Dual Crimson Katana",
    "Dual Crystal Greatblade",
    "Dual Crystal Hammer",
    "Dual Crystal Reaperblade",
    "Dual Cursed Blade",
    "Dual Cursed Scythe",
    "Dual Cyber Sickle",
    "Dual Cyborg Blade",
    "Dual Demonic Blade",
    "Dual Demonic Greatsword",
    "Dual Demonic Scythe",
    "Dual Depths Blaster",
    "Dual Desert Blade",
    "Dual Devil Katana",
    "Dual Divine Blaster",
    "Dual Divine Sword",
    "Dual Divinity Blade",
    "Dual Divinity Scythe",
    "Dual Draconic Blade",
    "Dual Draconic Twinblade",
    "Dual Dragon Slayer",
    "Dual Dragonfire Katana",
    "Dual Dreadborn Blade",
    "Dual Dreadborn Scythe",
    "Dual Easter Cannon",
    "Dual Easter Fans",
    "Dual Eclipse Blaster",
    "Dual Eclipse Gleam",
    "Dual Elemental Masterblade",
    "Dual Emerald Blade",
    "Dual Emperor's Lance",
    "Dual Eternal Blasters",
    "Dual Eternal Greatsword",
    "Dual Ether Blade",
    "Dual Evil Fans",
    "Dual Final Phase",
    "Dual Fire Blasters",
    "Dual Fire Katana",
    "Dual Firebloom Blade",
    "Dual Firebloom Scythe",
    "Dual Firework Blasters",
    "Dual Flower Katana",
    "Dual Flutter Blade",
    "Dual Frigid Blade",
    "Dual Frigid Scythe",
    "Dual Frog Blasters",
    "Dual Frost Kunai",
    "Dual Frost Saber",
    "Dual Frosted Gleam",
    "Dual Galaxy Nunchucks",
    "Dual Ghostfish Blade",
    "Dual Gleaming Katana",
    "Dual Gleaming Scythe",
    "Dual Gold Vanity Blade",
    "Dual Golden Fang",
    "Dual Good Fans",
    "Dual Gothic Bunny Blade",
    "Dual Gothic Bunny Scythe",
    "Dual Gravebone Blade",
    "Dual Gravebone Scythe",
    "Dual Green Energy Sword",
    "Dual Hacker Scythe",
    "Dual Hakai Blade",
    "Dual Hakai Set",
    "Dual Harmonic Set",
    "Dual Harmony Blades",
    "Dual Hazy Katana",
    "Dual Hazy Scythe",
    "Dual Heart Blade",
    "Dual Heartbreaker Blade",
    "Dual Heartbreaker Scythe",
    "Dual Heavenly Sword",
    "Dual Hellchain Blade",
    "Dual Hellchain Scythe",
    "Dual Holo Fan",
    "Dual Iced Energy Blades",
    "Dual Inferno Katana",
    "Dual Infinite Blade",
    "Dual Infinite Scythe",
    "Dual Ironrose Blade",
    "Dual Jolly Fan",
    "Dual Kitsune Blade",
    "Dual Kraken Blade",
    "Dual Kraken Scythe",
    "Dual Krampus Blade",
    "Dual Krampus Scythe",
    "Dual Kurogin Katana",
    "Dual Kurogin Scythe",
    "Dual Leviathan Set",
    "Dual Lightning Dagger",
    "Earth Blade",
    "Easter Cannon",
    "Easter Fan",
    "Easter Scythe",
    "Echoblade",
    "Eclipse Backsword",
    "Eclipse Blaster",
    "Eclipse Desire",
    "Eclipse Edge",
    "Eclipse Gleam",
    "Eclipse Reaver",
    "Eclipse Slayer",
    "Eclipse Warblade",
    "Eclipse Warden",
    "Eclipsion Blade",
    "Eclipsion Saber",
    "Ecliptarch",
    "Ecliptic Fang",
    "Egg Cutter",
    "Eggbeater Blade",
    "Eggcelent Saber",
    "Egged Staff",
    "Eggshell Shardblade",
    "Eggsplitter Blade",
    "Eldermarine Blade",
    "Electric Blade",
    "Electric Ice Blade",
    "Electric Reaver",
    "Electric Sunblade",
    "Electricity Blade",
    "Electroclash Blade",
    "Elemental Masterblade",
    "Elemental Sword",
    "Ember's Rage",
    "Emberfang Blade",
    "Emberflare Blade",
    "Emberstrike",
    "Embroided Slasher",
    "Emerald Blade",
    "Emerald Edge",
    "Emerald Eggblade",
    "Emerald Greatsword",
    "Emerald Katana",
    "Emerald Parasol",
    "Emerald Pixelpiercer",
    "Emerald Valor",
    "Emerald Warden Blade",
    "Emperor Blade",
    "Emperor's Axe",
    "Emperor's Lance",
    "Empyrean Fortress",
    "Empyrean Greatblade",
    "Enchanted Axe",
    "Enchanted Backblade",
    "Enchanted Cleaver",
    "Enchanted Greatsword",
    "Enchanted Roseblade",
    "Entangled Axe",
    "Equinox Ball Kebab",
    "Essence Cleaver",
    "Eternal Autumn",
    "Eternal Ice",
    "Eternal Nightmare",
    "Eternal Piercer",
    "Eternal Scythe",
    "Eternal Shield",
    "Eternal Slasher",
    "Eternal Spark",
    "Eternal Staff",
    "Eternum Galepiercer",
    "Ether Blade",
    "Ethereal Bombardment",
    "Ethereal Kitsune Blade",
    "Ethereal Sovereign",
    "Etherium Dagger",
    "Everbloom Fang",
    "Everflame Scythe",
    "Everflourescent Blade",
    "Everfrost Scythe",
    "Evergreen Edge",
    "Evergreen Greatblade",
    "Evil Runics Blade",
    "Evolved Dragon Sword",
    "Evolved Royal Sword",
    "Evolved Spiked Club",
    "Excalibur",
    "Executive Greatsword",
    "Exo-Godslayer",
    "Failsafe",
    "Fallen Angel",
    "Fallen Cherub's Blade",
    "Fallen Sword",
    "Fallwake",
    "Fantasy Katana",
    "Feastbringer",
    "Festive Blade",
    "Festive Bow",
    "Festive Chakram",
    "Festive Cutter",
    "Festive Eclipse Blade",
    "Festive Sword",
    "Festive Valor Sword",
    "Final Phase",
    "Fire Blade",
    "Fire Dragon",
    "Fire Fang Blade",
    "Fire Katana",
    "Fire Mech's Staff",
    "Firebloom Blade",
    "Firebloom Scythe",
    "Firebrand",
    "Firework Blaster",
    "Firework Edge",
    "Firework Fang",
    "Firework Fighter",
    "Firework Spear",
    "Fish",
    "Flame Blade",
    "Flamechip Blade",
    "Flaming Sword",
    "Flamingo Slayer",
    "Flood Serpent",
    "Floppy Chicken",
    "Floral Slicer",
    "Floral Tempest Blade",
    "Flower Katana",
    "Flower Sword",
    "Flowering Sword",
    "Flowing Fists",
    "Flowing Katana",
    "Flowing Waterblade",
    "Flutter Blade",
    "Flutter Bow",
    "Forest Fang",
    "Forsaken Riftide",
    "Fortunate Sword",
    "Fortune Blade",
    "Fortune Carver",
    "Fortune Cleaver",
    "Fortune Seeker",
    "Fortune Splitter",
    "Foxfang Dagger",
    "Fracture Blade",
    "Fractured Protocol",
    "Fragmented Wallblade",
    "Frigid Blade",
    "Frigid Scythe",
    "Frog",
    "Frog Blaster",
    "Frog Sword",
    "Frost Blaster",
    "Frost Dragon",
    "Frost Kunai",
    "Frost Monarch Saber",
    "Frost Reaper",
    "Frost Spark Saber",
    "Frostbane",
    "Frostbite Annihilator",
    "Frostbite Blade",
    "Frostbite Edge",
    "Frostbite Shard",
    "Frostbite Slash",
    "Frostblade",
    "Frostbloom Lance",
    "Frostbound Lantern",
    "Frostbound Regal Edge",
    "Frostbrand Saber",
    "Frosted Antler",
    "Frosted Blade",
    "Frosted Cards",
    "Frosted Gleam",
    "Frosted King",
    "Frosted Maul",
    "Frostlight Greatblade",
    "Frostreaver",
    "Frostshard Blade",
    "FROSTWALL",
    "Frostwraith",
    "Frosty Dagger",
    "Frozen Doomblade",
    "Frozen Eternity",
    "Frozen Gale",
    "Frozen Star",
    "Frozen Void",
    "Frying Pan",
    "Fury Claw",
    "Futuristic Edge",
    "Galactic Emperor",
    "Galactic Halberd",
    "Galactic Harbinger",
    "Galactic Veilpiercer",
    "Galactical Rapier",
    "Galaxy Nunchucks",
    "Gale Sabre",
    "Ghost Slicer",
    "Ghostfang",
    "Ghostfish Blade",
    "Ghostfish Bow",
    "Ghostly Vengeance",
    "Ghostwalker",
    "Ghoul Cleaver",
    "Gigantic Cleaver",
    "Gilded Glory",
    "Gilded Harvest",
    "Gingerbread Guardian",
    "Glacial Blade",
    "Glacial Crown",
    "Glacial Dominance",
    "Glacial Fang",
    "Glacial Hunter",
    "Glacial Scythe",
    "Glacial Shard",
    "Glacial Slasher",
    "Glacial Spike",
    "Glacial Strike",
    "Glacialis Requiem",
    "Glacier Reaper",
    "Glacier Shard",
    "Glacier Staff",
    "Gladiator Sword",
    "Gleaming Katana",
    "Gleaming Scythe",
    "Glimmeredge",
    "Glitch Sabre",
    "Glittering Horizon",
    "Glowy Bone",
    "Gobble Blade",
    "Godsaber",
    "Gold Vanity Blade",
    "Gold Vanity Spear",
    "Golden Axe",
    "Golden Ban Hammer",
    "Golden Blade",
    "Golden Champion",
    "Golden Crescent Bow",
    "Golden Dualblade",
    "Golden Eggsmite",
    "Golden Fang",
    "Golden Flare",
    "Golden Gauntlets",
    "Golden Harvest",
    "Golden Hour Blade",
    "Golden Rapier",
    "Golden Scythe",
    "Golden Slasher",
    "Golden Snapper",
    "Golden Sword",
    "Golden Twinblade",
    "Good Fan",
    "Gothic Bunny Blade",
    "Gothic Bunny Scythe",
    "Grass Blade",
    "Gravebone Blade",
    "Gravebone Scythe",
    "Gravelight",
    "Gravestone",
    "Grayscale Sword",
    "Greatsword of the Depths",
    "Green Energy Sword",
    "Green Ninja Katana",
    "Green Ninja Star",
    "Greenleaf Saber",
    "Griffin's Claw",
    "Grim Sever",
    "Guardian of Love",
    "Guardian of the Underworld",
    "Guardian Spear",
    "Gull Wing",
    "Hacker Scythe",
    "Hakai Blade",
    "Hakai Scorpion",
    "Halberd",
    "Hallow's Blaster",
    "Hallow's Edge",
    "Hammer of Light",
    "HardRockStick",
    "Harmonic Fan",
    "Harmonic Staff",
    "Harmony Blade",
    "Harvest Cutter",
    "Harvest Glow",
    "Harvest Reaper",
    "Haunted Harvester",
    "Haunting Edge",
    "Hazy Katana",
    "Hazy Scythe",
    "Headless Horror",
    "Heart Blade",
    "Heart Bow",
    "Heart of Winter",
    "Heart Wand",
    "Heartbreaker Blade",
    "Heartbreaker Scythe",
    "Heavenly Blade",
    "Heavenly Chakram",
    "Heavenly Sword",
    "Hellbound Cleaver",
    "Hellchain Blade",
    "Hellchain Scythe",
    "Hellfire Blade",
    "Hellfire King",
    "Hellfire Shadowslicer",
    "Hellwing Set",
    "Hex Slicer",
    "Hexblade",
    "Higanbana Katana",
    "Hitman",
    "Holiday Herald",
    "Hollow Blade",
    "Hollow Oath Katana",
    "Hollow Wind Katana",
    "Holo Fan",
    "Holographic Sword",
    "Holy Axe",
    "Holy Blade",
    "Holy Emberblade",
    "Holy Lance",
    "Holy Runic Blade",
    "Holy Sword",
    "Holy Trident",
    "Hooded Blade",
    "Hope's Blade",
    "Horizon Reaper",
    "Horseman's Sword",
    "Hotdog Sword",
    "Hydrocore",
    "Hyperblade Prototype",
    "Hyperion Blade",
    "Hyperion Saber",
    "Icarus' Scythe",
    "Ice Blade",
    "Ice Carver",
    "Ice Dagger",
    "Ice King Staff",
    "Ice King's Bow",
    "Ice Mage Staff",
    "Ice Warrior",
    "Icebound Dominus",
    "Iced Avenger",
    "Iced Katana",
    "Iced Shard",
    "Icicle Strike",
    "Icy Puck Blade",
    "Illumina",
    "Imperial Monarch",
    "InceptionTime's Hammer",
    "Infectious Edge",
    "Inferna Spine",
    "Infernal Devotion",
    "Infernal Edge",
    "Infernal Fang",
    "Infernal Slicer",
    "Inferno Axe",
    "Inferno Blade",
    "Inferno Emberblade",
    "Inferno Greatscythe",
    "Inferno Katana",
    "Inferno Lance",
    "Inferno Reaver",
    "Inferno Scythe",
    "Inferno Sword",
    "Infinite Blade",
    "Infinite Scythe",
    "Infinity Staff",
    "Infinity Sword",
    "Inkborn Howl",
    "Inksoul Brush",
    "Iridescent Stormblade",
    "Iron Pixelblade",
    "Iron Pixelbrand",
    "Iron Reaver",
    "Ironblood Arsenal",
    "Ironhowl",
    "Ironrose Blade",
    "Ironrose Lance",
    "Jack's Grin",
    "Jackolantern",
    "Jaded Staff",
    "Jellybean Jabber",
    "Jellyfish Parasol",
    "Jeweled Blade",
    "Jolly Fan",
    "Jolly Scythe Set",
    "Katana of Hearts",
    "Katana of the Red Flames",
    "Keyblade",
    "Khage's Blade",
    "King Blade",
    "King's Valor",
    "Kingdom's Blade",
    "Kingsguard's Edge",
    "Kitchen Knife",
    "Kitsune",
    "Kitsune Blade",
    "Kitty Launcher",
    "Knight's Crest",
    "Kong's Axe",
    "Kraken",
    "Kraken Blade",
    "Kraken Fang",
    "Kraken Scythe",
    "Kraken's Shard",
    "Kraken's Wraith",
    "Krampus Blade",
    "Krampus Scythe",
    "Kurogin Katana",
    "Kurogin Scythe",
    "Lantern Breaker",
    "Lantern Rapier",
    "Lantern's Grasp",
    "Laser Twinblade",
    "Lava Blade",
    "Lava Lamp Staff",
    "Leader's Icebow",
    "Leafsong",
    "LEGO® Axe",
    "LEGO® Greatsword",
    "LEGO® Hammer",
    "LEGO® Spear",
    "LEGO® Staff",
    "LEGO® Sword",
    "Lightning Cards",
    "Lightning Dagger",
    "Lightning Kunai",
    "Lightning Sickle",
    "Lightwalker",
    "Lily Blade",
    "Lily Katana",
    "Lily Parasol",
    "Lirilì Larilà Blade",
    "Lollipop Lacerator",
    "Long-nosed Scythe",
    "Lost Sword",
    "Love Blade",
    "Love Sickle",
    "Loveclaw Blade",
    "Loveclaw Scythe",
    "Lover's Axe",
    "Lovescythe",
    "Loving Backblade",
    "Loyal Oathblade",
    "Lucky Dagger",
    "Lucky Fan",
    "Lucky Fang",
    "Lumen Petal",
    "Lumenshell Blade",
    "Lumenshell Scythe",
    "Lumenwing Blade",
    "Lumenwing Bow",
    "Lumina Blade",
    "Lumina Bow",
    "Lumina Spear",
    "Luminous Edge",
    "Lunar Aegis",
    "Lunar Blade",
    "Lunar Bloom",
    "Lunar Fan",
    "Lunar New Year Fury",
    "Lunar Parasol",
    "Lunaris Fang",
    "Luv4Pain Blade",
    "Luv4Pain Scythe",
    "Magma Blade",
    "Magma Splitter",
    "Malice Blade",
    "Malice Parasol",
    "Maple Blade",
    "Maple Reaper",
    "Maple Strike",
    "Mariner's Blade",
    "Masksplitter",
    "Massive Lollipop",
    "Mech Laser Cannon",
    "Mech Staff",
    "Mecha Axe",
    "Mechslayer Blade",
    "Melody of Ruin",
    "Melon Slice",
    "Meltinglight",
    "Meme Destroyer",
    "Merry Gleam",
    "Meteoric Spike",
    "Midas Thorn",
    "Midnight Cleaver",
    "Midnight Fang",
    "Midnight Reaver",
    "Midsummer Blade",
    "Molten Greatblade",
    "Molten Slayer",
    "Monarch Blade",
    "Monarch Shield",
    "Moonbeam Blade",
    "Moonbeam Bow",
    "Moonflower Greatsword",
    "Moonflower Katana",
    "Moonlight Blade",
    "Moonlight Bliss",
    "Moonlight Bow",
    "Moonlit Blossom Blade",
    "Moral Duality",
    "Morbid Mireblade",
    "Morningdew Edge",
    "Mortal's Demise",
    "Mothyx Blade",
    "Mothyx Scissors",
    "Mummy's Curse",
    "Mummy's Slasher",
    "Musara",
    "Mushroom Bat",
    "Mystical Crossbow",
    "Mythic Eggclipse",
    "Nano Katana",
    "Nature Cards",
    "Nature Kunai",
    "Nature's Fang",
    "Naturic Cutlass",
    "Nebula Blade",
    "Nebula Blaster",
    "Nebula Bow",
    "Nebula Claws",
    "Nebula Fan",
    "Nebula Katana",
    "Nebula Nightblade",
    "Nebula Scythe",
    "Nebula Shard",
    "Nebula Slasher",
    "Nebula Sniper",
    "Nebula Staff",
    "Nebula Sword",
    "Nebula Warrior",
    "Nebula Yoru",
    "Nebula's Lightning",
    "Necroshard Blade",
    "Nemesis Blade",
    "Neo-Neko Katana",
    "Neon Shard",
    "Neon Viper",
    "Netherfang",
    "New Dawn Reaver",
    "New Year's Axe",
    "New Year's Katana",
    "New Year's Lance",
    "New Year's Resolve",
    "New Year's Set",
    "New Year's Sickles",
    "New Year's Slasher",
    "New Year's Spear",
    "New Years Blade",
    "New Years Fan",
    "New Years Greatsword",
    "New Years Slicer",
    "New Years Staff",
    "Night Raver",
    "Nightclaw Blade",
    "Nightclaw Scythe",
    "Nightfall Violin",
    "Nightlash",
    "Nightmare Cleaver",
    "Nightmare Reaver",
    "Nightmare's Bite",
    "Nightmare's Slash",
    "Nightpiercer",
    "Nightshade",
    "Nightshade Edge",
    "Nightshade Fang",
    "Nimbus Spear",
    "Ninja Shuriken",
    "Noob",
    "Noodle Nuisance",
    "North Blade",
    "North Pole Enchanter",
    "North Star",
    "Northern Blade",
    "Northern Fury",
    "Northern Warrior",
    "Northstar Reaper",
    "Nothing",
    "Null Dagger",
    "Null Fang",
    "Null Riftblade",
    "Nyxpetal Blade",
    "Nyxpetal Fan",
    "Oathblade",
    "Oblivion Edge",
    "Oblivion Fang",
    "Oblivion Pike",
    "Oblivion Scythe",
    "Obsidian Blade",
    "Obsidian Scythe",
    "Obsidian Wrath",
    "Ocean Blade",
    "Ocean Dagger",
    "Ocean Guitar",
    "Ocean's Fury",
    "Ocean's Lament",
    "Oceanic Reaper",
    "Ogre's Axe",
    "Omega Edge",
    "Ominous Blade",
    "Oni Claws",
    "Oni Ghost",
    "Oni's Pact",
    "Oniwake",
    "Onyx Katana",
    "Opal Leviathan",
    "Opal Staff",
    "Orange Phoenixblade",
    "Orbit Spear",
    "Ornament Crushers",
    "Overclocked",
    "Overgrown Scythe",
    "Paladin's Sword",
    "Palmcleaver",
    "Papa Smurfs Shield",
    "Parasitic Dagger",
    "Parasitic Scythe",
    "Parasol",
    "Party Popper",
    "Passionfang Edge",
    "Pastel Bow",
    "Pastel Spear",
    "Peachborne Blade",
    "Peachborne Fan",
    "Pearl Dagger",
    "Pearl Shard",
    "Peasant's Blade",
    "Peep Saber",
    "Penguin",
    "Periastron's Glory",
    "Permafrost Blade",
    "Permafrost Flowerblade",
    "Permafrost Katana",
    "Permafrost Staff",
    "Persistence Blade",
    "Petalblade",
    "Phantom Blade",
    "Phantom Edge",
    "Phantom Greatsword",
    "Phantom Reaver",
    "Phantom Saber",
    "Phantom Scythe",
    "Phantom Warrior",
    "Phoenix Blade",
    "Phoenix Rebirth",
    "Phoenix Scythe",
    "Pickaxe",
    "Pillar",
    "Pillow",
    "Pine Spirit",
    "Pink Dagger",
    "Pink Ninja Katana",
    "Pink Ninja Star",
    "Pink Oni Katana",
    "Pirate King's Cutlass",
    "Pixel Blaster",
    "Plague Slayer",
    "Plasma Beam Blade",
    "Plasma Blaster",
    "Plasma Gauntlets",
    "Plasma Katana",
    "Plasma Spear",
    "Platinum Staff",
    "Play Sword",
    "Plunger",
    "Poison Blade",
    "Poison Greatsword",
    "Poison Ivy",
    "Poisoned Bunny",
    "Polar Bear",
    "Polar Cleaver",
    "Polar Fury",
    "Polar King's Blade",
    "Poseidon's Trident",
    "Potato",
    "Pretty Princess Wand",
    "Prince Blade",
    "Princess Fan",
    "Princess Katana",
    "Prismatic Gem Blade",
    "Prismatic Gem Scythe",
    "Prismatic Harvester",
    "Prismatic Katana",
    "Prismatic Odachi",
    "Prismshard Blade",
    "Progression Scythe",
    "Pulseheart Set",
    "Pumpkin Blade",
    "Pumpkin Fan",
    "Pumpkin Reaper",
    "Pumpkin VineCrusher",
    "Puppy",
    "Purity Blade",
    "Purity Bow",
    "Purple Flameblade",
    "Purple Oni Katana",
    "Purple Sunblade",
    "Quasar Piercer",
    "Queen Blade",
    "Radiant Countdown",
    "Radiant Edge",
    "Radiant Veil",
    "Raging Tempest",
    "Raincaller Blade",
    "Ranked Season 1 Top 1",
    "Ranked Season 1 Top 200",
    "Ranked Season 1 Top 50",
    "Ranked Season 10 Champion",
    "Ranked Season 10 Top 1",
    "Ranked Season 10 Top 200",
    "Ranked Season 10 Top 50",
    "Ranked Season 11 Champion",
    "Ranked Season 11 Top 1",
    "Ranked Season 11 Top 200",
    "Ranked Season 11 Top 50",
    "Ranked Season 12 Champion",
    "Ranked Season 12 Top 200",
    "Ranked Season 12 Top 50",
    "Ranked Season 13 Champion",
    "Ranked Season 13 Top 1",
    "Ranked Season 13 Top 200",
    "Ranked Season 13 Top 50",
    "Ranked Season 14 Champion",
    "Ranked Season 14 Top 1",
    "Ranked Season 14 Top 200",
    "Ranked Season 14 Top 50",
    "Ranked Season 15 Champion",
    "Ranked Season 15 Top 1",
    "Ranked Season 15 Top 200",
    "Ranked Season 15 Top 50",
    "Ranked Season 16 Champion",
    "Ranked Season 16 Top 1",
    "Ranked Season 16 Top 200",
    "Ranked Season 16 Top 50",
    "Ranked Season 17 Champion",
    "Ranked Season 17 Top 1",
    "Ranked Season 17 Top 200",
    "Ranked Season 17 Top 50",
    "Ranked Season 18 Champion",
    "Ranked Season 2 Top 1",
    "Ranked Season 2 Top 200",
    "Ranked Season 2 Top 50",
    "Ranked Season 3 Top 1",
    "Ranked Season 3 Top 200",
    "Ranked Season 4 Top 1",
    "Ranked Season 4 Top 100",
    "Ranked Season 4 Top 25",
    "Ranked Season 5 Champion",
    "Ranked Season 5 Top 1",
    "Ranked Season 5 Top 200",
    "Ranked Season 5 Top 50",
    "Ranked Season 6 Top 1",
    "Ranked Season 7 Top 1",
    "Ranked Season 8 Champion",
    "Ranked Season 8 Top 1",
    "Ranked Season 8 Top 200",
    "Ranked Season 8 Top 50",
    "Ranked Season 9 Champion",
    "Ranked Season 9 Top 1",
    "Ranked Season 9 Top 200",
    "Ranked Season 9 Top 50",
    "Rapier",
    "Raven Greatsword",
    "Raven Scythe",
    "Reaper's Edge",
    "Reaper's Scythe",
    "Reckoner Scythe",
    "Red Guardian Bow",
    "Red Moon Katana",
    "Red Ninja Katana",
    "Red Ninja Star",
    "Red Oni Katana",
    "Red Saber",
    "Redstone Sword",
    "Redwake Fang",
    "Regret Blades",
    "Reindeer",
    "Reindeer Blade",
    "Reindeer Hammer",
    "Relic Scythe",
    "Relicblade of Renewal",
    "Remastered Linked Sword",
    "Resolution Blade",
    "Resolution Reaver",
    "Resolution Rumble Champion",
    "Resolution Rumble Warrior",
    "Resurrection Blade",
    "Resurrection Scythe",
    "Retribution Guitar",
    "Retro Backblade",
    "Revenant's Vow",
    "Ribbon Blade",
    "Ribbon Shield",
    "Ricefield Cutter",
    "Rifle",
    "Riftflare Katana",
    "Riftspike Reaper",
    "Robotic Arm",
    "Rockxcalibur",
    "Rosarium Blade",
    "Rose Axe",
    "Rose Backsword",
    "Rose Blade",
    "Rose Bow",
    "Rose Greatsword",
    "Rose Piercer",
    "Rose Pinksaber",
    "Rose Railgun",
    "Rose Twinblade",
    "Rose Wand",
    "Rosefire Blade",
    "Rosefire Scythe",
    "Royal Duality",
    "Royal Pixelblade",
    "Royal Sharpened Sword",
    "Royal Sovereign",
    "Royal Sword",
    "Rubber Chicken",
    "Ruby Cutter",
    "Ruby Greataxe",
    "Runebreaker Staff",
    "Runesteel",
    "Runic Blade",
    "Runic Dragonslayer",
    "Runic Longsword",
    "Runic Redblade",
    "Runic Scythe",
    "Runic Slasher",
    "Runic Wrecker",
    "Russo's Sword of Truth",
    "Rusted Will",
    "Rusty Saber",
    "Sabrina's Sword of Healing",
    "Sakura Fan",
    "Sakura Katana",
    "Sakura Parasol",
    "Sakura Scythe",
    "Sakura's Requiem",
    "Saltpiercer",
    "Samurai Bow",
    "Samurai Katana",
    "Samurai's Backblade",
    "Samurai's Set",
    "Samurai's Sickle",
    "Sandstorm Slasher",
    "Santa's Greatsword",
    "Santa's Slicer",
    "Santa's Wrecker",
    "Savior Greatsword",
    "Scaled Longsword",
    "Scarab's Wrath",
    "Scarlet Fury",
    "Sci Fi Axe",
    "Sci Fi Blade",
    "Scion's Grasp",
    "Scorpion Staff",
    "Scourge of the Seas",
    "Sea Turtle",
    "Seafoam Cutter",
    "Seeker's Edge",
    "Seraph's Blade",
    "Seraphim",
    "Serene Blade",
    "Serene Scythe",
    "Serenity Blade",
    "Serpent",
    "Serpent's Fang",
    "Serpent's Greatsword",
    "Serpent's Katana",
    "Serpent's Lance",
    "Serpent's Shiv",
    "Serpent's Sickle",
    "Serpent's Slicer",
    "Serpent's Wraithblade",
    "Serpents Fan",
    "Serpents Staff",
    "Servant's Dagger",
    "Shackled Celestial",
    "Shadepiercer",
    "Shadow Cards",
    "Shadow Dagger",
    "Shadow Fang",
    "Shadow Kunai",
    "Shadow Mirage",
    "Shadow Monarch Blade",
    "Shadow Monarch Bow",
    "Shadowborn Crate",
    "Shadowcleaver",
    "Shadowed Slasher",
    "Shardfang",
    "Shark",
    "Shark Blade",
    "Shattered Edge",
    "Shattered Sword",
    "Shatterflight Bird",
    "Shatterthorn",
    "Shell Slicer",
    "Sheriff's Revolver",
    "Shinobi Stick",
    "Shinobi's Curse",
    "Siam Ember Axe",
    "Siamese Edgeblade",
    "Silent Fang",
    "Silent Peak",
    "Silk Divinity Blade",
    "Silk Divinity Bow",
    "Silken Fang",
    "Silver Blade",
    "Silver Strike",
    "Singularity Fang",
    "Singularity Katana",
    "Singularity Scythe",
    "Sinister Blade",
    "Sinister Blaster",
    "Sinkcleaver",
    "Skeletal Slicer",
    "Skeleton's Cutlass",
    "Skib",
    "Skull King",
    "Skullsplitter",
    "Sky Edge",
    "Skyfall's Edge",
    "Sleek Slicer",
    "Slime",
    "Slime Sword",
    "Small Sapling",
    "Snowball Cannon",
    "Snowball Cleaver",
    "Snowball Launcher",
    "Snowboard Edge",
    "Snowbound Shard",
    "Snowflake Edge",
    "Snowman Blade",
    "Snowman Scythe",
    "Snowstorm Blade",
    "Snowstorm Sabre",
    "Snowveil Blade",
    "Snowveil Scythe",
    "Solans",
    "Solar Cleaver",
    "Solar Edge",
    "Solar Flare Blade",
    "Solar Iceblade",
    "Solara Sword",
    "Solarflare Glaive",
    "Solarflare Saber",
    "Solaris Edge",
    "Solaris Halo",
    "Solaris Lance",
    "Solarus",
    "Solbane Edge",
    "Solblade Sentinel",
    "Soul Blade",
    "Soul Reaver",
    "Soul Scythe",
    "Soul Sword",
    "Soulbinder's Edge",
    "Soulbloom Blade",
    "Soulbloom Scissors",
    "Soulless Katana",
    "Soulreaper's Scythe",
    "Soulrender Scythe",
    "Soulshredder",
    "Spark Sword",
    "Sparkle Saber",
    "Sparkler Saber",
    "SPARKLERR",
    "Spearbeard",
    "Specter's Oath",
    "Spectral Fang",
    "Speed Striker",
    "Spiked Club",
    "Spinalis",
    "Spirit Blade",
    "Spiritbloom Dagger",
    "Spiritbound Katana",
    "Spooky Sightblade",
    "Spring Blade",
    "Spring Championblade",
    "Spring Runicblade",
    "Spring Slicer",
    "Spring Sun Bow",
    "Spring Sun Scythe",
    "Springbloom Saber",
    "SpyderSammy",
    "Staff of Despair",
    "Staff of The Accursed",
    "Staff of the Worthy",
    "Star Crusher",
    "Star Wand",
    "Starbloom Blade",
    "Starbloom Scythe",
    "Stardust Bow",
    "Stardust Katana",
    "Starfall",
    "Starlight Axe",
    "Starlight Saber",
    "Starlight Scythe",
    "Starlight Spear",
    "Starry Sword",
    "Starscope Sniper",
    "Starshooter Rapier",
    "Stellacore",
    "Stellar Blade",
    "Stellar Guard",
    "Stellar Revolver",
    "Stick",
    "Stone Aeroblades",
    "Stone Katana",
    "Stone Nunchucks",
    "Stone Scythe",
    "Stop Sign",
    "Storm Bringer",
    "Storm Slicer",
    "Stormbane",
    "Stormbreaker Claymore",
    "Stormforged Shortblade",
    "Stormlash",
    "Stormpiercer",
    "Stormpiercer Blade",
    "Stormreign",
    "Stormveil",
    "Stratocaster Electric Guitar",
    "Stratus Blade",
    "Strawberry Cake Blade",
    "Strawberry Cake Lance",
    "Streamblade",
    "Subversion",
    "Summer Fan",
    "Summer Scythe",
    "Sunbloom Cutter",
    "Sundue Slash",
    "Sunfire Sword",
    "Sunfire's Flare",
    "Sunflare Katana",
    "Sunken Shard",
    "Sunkissed Scythe",
    "Sunknight's Sword",
    "Sunny Saber",
    "Sunny Sword",
    "Sunset Katana",
    "Sunset Pastelblade",
    "Sunspike",
    "Super Bow",
    "Super Horizon",
    "Super Quantum",
    "Super Sunslayer",
    "Supercharged Voltblade",
    "Survivor's Fang",
    "Sword of Order",
    "Sword of the Sun",
    "Sylvan Blade",
    "Synth Saber",
    "T-Rex",
    "Tanto",
    "Teal Longsword",
    "Techblade",
    "Techno Fang",
    "Tempest Cutter",
    "Temple Cleaver",
    "Temporal Eggblade",
    "Temporal Shard",
    "The Abyss",
    "The Conjurer",
    "The Covenant",
    "The Curse",
    "The Frozen Monarch",
    "The Nooblade",
    "Thornblade",
    "Thorned Coilblade",
    "Thorned Sovereign",
    "Thornling Dagger",
    "Thronebreaker",
    "Thunder Blade",
    "Thunder Spear",
    "Thunderfall Edge",
    "Thunderous Hammer",
    "Tidal Slicer",
    "Tidepiercer",
    "Tidewither",
    "Tiger's Katana",
    "Tigershadow Blade",
    "Time Stopper",
    "Timeless Greatsword",
    "Titan Dagger",
    "Titan Fang",
    "Titan's Gleam",
    "Titanfall Edge",
    "Titansteel Saber",
    "Tomb of the Nine Kings",
    "Torn Sutra",
    "Toxic Fang",
    "Toxic Greatsword",
    "Toxic Mirage",
    "Toxic Tendril",
    "Training Stick",
    "Trench Saber",
    "Trenchreaver",
    "Trident",
    "Trinity Axe",
    "Triple Devil Katana",
    "Tsunami Blade",
    "Tulip Cleaver",
    "TUNG TUNG TUNG SAHUR",
    "Turkey Slayer",
    "Twilight Bite",
    "Twilight Blade",
    "Twilight Edge",
    "Twilight Saber",
    "Twilight Scythe",
    "Twilight Slasher",
    "Twilight Tanto",
    "Twisted Rosemary Blade",
    "Ultimate Ruby",
    "Umbra Spear",
    "Umbral Bloom",
    "Undead Blade",
    "Unstable Blade",
    "Valkyrien Blade",
    "Valkyrien Scythe",
    "Valor's Rage",
    "Vampire Saw",
    "Vampire Sickle",
    "Vanguard Edge",
    "Vanguard Shield",
    "Vanguard's Blade",
    "Vaporwave Blade",
    "Vaporwave Crusher",
    "Vengeful Dagger",
    "Venom Blade",
    "Venom Edge",
    "Venomlight Scythe",
    "Venomsanct",
    "Venomshank",
    "Venomspike Aegis",
    "Verdant Bloom Saber",
    "Verdant Halberd",
    "Verdant Saber",
    "Verdraith",
    "Violet Crusher",
    "VIP Cutlass",
    "VIP Sword",
    "Viral Edge",
    "Viral Piercer",
    "Vishram",
    "Void Blade",
    "Void Circuit Blade",
    "Void Engine Blade",
    "Void Eyes",
    "Void Guardian",
    "Void Reaver",
    "Void Scythe",
    "Void Shard",
    "Void Sword",
    "Void Vanguard",
    "Void Weaver",
    "Voidborn",
    "Voidborn Reaver",
    "Voidbringer",
    "Voided Greatscythe",
    "Voided Saber",
    "Voided Veilpiercer",
    "Voidflare Blade",
    "Voidheart Piercer",
    "Voidhowler",
    "Voidhunter Scythe",
    "Voidshard Blade",
    "Voidshard Bow",
    "Voidshatter",
    "Voidstrike Blade",
    "Voidwalker Blade",
    "Voidweaver's Fang",
    "Volcanic Axe",
    "Voltage",
    "Voltage Edge",
    "Voltfire Blade",
    "Voltfire Lash",
    "Vortex Fang",
    "Vortex Striker",
    "Warlord's Cache",
    "Water Blade",
    "Water Bow",
    "Water Slasher",
    "Wavelight Greatblade",
    "Wealth Cutter",
    "Whispering Katana",
    "Whispering Oak",
    "Whispers of the Fallen",
    "Whitefire Blade",
    "Whitefire Cleaver",
    "Wicked Crow",
    "Wicked Reaper",
    "Wicked Thorn",
    "Wildheart",
    "Willowfang",
    "Wind Slicer",
    "Wind Thorn",
    "Windforce",
    "Winged Blade",
    "Winged Sword",
    "Winged Warrior",
    "Winter Blaster",
    "Winter Katana",
    "Winter Sovereign Blade",
    "Winter Warrior",
    "Winter Wolf",
    "Winter's Aurora",
    "Winter's Bite",
    "Winter's Wrath",
    "Wintery Greatblade",
    "Wispwind Reaper",
    "Wisteria Blade",
    "Wisteria Parasol",
    "Witch's Broom",
    "Witch's Broomstick",
    "Witch's Curse",
    "Witch's Set",
    "Withered Chakram",
    "Wolf Gladius",
    "Wolf Greatsword",
    "Wonderwisp Greatsword",
    "Wooden Hammer",
    "Wraith's Edge",
    "Wraith's Reaver",
    "Wraith's Whisper",
    "Y2K Blade",
    "Yin Yang Cleaver",
    "Yin Yang Greatsword",
    "Yin Yang Katana",
    "Yin Yang Parasol",
    "Yin Yang Scythe",
    "Yokai Fang",
    "Yokai Thread",
    "Yolk Saber",
    "Yolkbane",
    "Yolkheart Blade",
    "Yuleflame",
    "Yuletide Saber",
    "Zephyr Blade",
    "Zephyr Scythe",
    "Zero Saber",
    "Zeus' Lightning",
    "Zodiac Blade",
    "Zodiac Parasol",
    "Zombie Leg",
    "Zoru",
}
